### ISSUE TITLE
Implementation

### ISSUE THREAD

**Issue by frcsbdx** [stefanalt/RP2040-PIO-1-Wire-Master#1]
Hello, I'm tring to work with your interresting program.
Question: how and what's the GPIO to connect a DS18B20 to the pico ?

**Comment by stefanalt** [comment]
You can choose them freely. In the example code, I use pin 15 for the 1wire signal and pin 14 to control the
external transistor.

    /* Onewire config */
    offset_1wire = pio_add_program(pio, &onewire_program);
    owobj1.pio = pio;
    owobj1.sm = 2;
    owobj1.offset = offset_1wire;
    owobj1.pin = 15;
    owobj1.pinctlz = 14;

You need a circuit like this (ferrites, fuses might be ommited at your discretion)
![1wire](https://user-images.githubusercontent.com/13458707/151065801-28509bdf-fe3a-409c-86a3-9ae4c2c8544f.png)
